package berryallan.theflashmod.items;

import berryallan.theflashmod.handlers.CreativeTabHandler;
import berryallan.theflashmod.handlers.SpeedForceHandler;
import net.minecraft.block.BlockBed;
import net.minecraft.block.BlockDoor;
import net.minecraft.block.BlockStairs;
import net.minecraft.block.state.IBlockState;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.init.Blocks;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.ActionResult;
import net.minecraft.util.EnumActionResult;
import net.minecraft.util.EnumFacing;
import net.minecraft.util.EnumHand;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;

public class ItemBarryAllenLabSpawner extends Item
{
	public ItemBarryAllenLabSpawner(String id)
	{
		this.maxStackSize = 1;
		this.setCreativeTab(CreativeTabHandler.tabFlash);
	}
	
	public ActionResult<ItemStack> onItemRightClick(ItemStack itemstackIn, World world, EntityPlayer playerIn,
			EnumHand hand)
	{
		int x = (int) playerIn.posX;
		int y = (int) playerIn.getEntityBoundingBox().minY;
		int z = (int) playerIn.posZ;
		
		world.setBlockState(new BlockPos(x + 0, y + 0, z + 0), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 0, z + 0), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 0, z + 0), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 0, z + 0), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 0, z + 0), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 0, z + 0), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 0, z + 0), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 0, z + 0), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 0, z + 1), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 0, z + 1), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 0, z + 1), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 0, z + 1), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 0, z + 1), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 0, z + 1), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 0, z + 1), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 0, z + 1), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 0, z + 2), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 0, z + 2), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 0, z + 2), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 0, z + 2), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 0, z + 2), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 0, z + 2), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 0, z + 2), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 0, z + 2), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 0, z + 3), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 0, z + 3), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 0, z + 3), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 0, z + 3), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 0, z + 3), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 0, z + 3), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 0, z + 3), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 0, z + 3), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 0, z + 4), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 0, z + 4), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 0, z + 4), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 0, z + 4), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 0, z + 4), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 0, z + 4), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 0, z + 4), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 0, z + 4), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 0, z + 5), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 0, z + 5), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 0, z + 5), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 0, z + 5), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 0, z + 5), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 0, z + 5), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 0, z + 5), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 0, z + 5), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 0, z + 6), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 0, z + 6), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 0, z + 6), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 0, z + 6), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 0, z + 6), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 0, z + 6), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 0, z + 6), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 0, z + 6), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 0, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 0, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 0, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 0, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 0, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 0, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 0, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 0, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 0, z + 8), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 0, z + 8), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 0, z + 8), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 0, z + 8), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 0, z + 8), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 0, z + 8), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 0, z + 8), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 0, z + 8), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 1, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 1, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 1, z + 0), Blocks.brick_block.getDefaultState(), 0);
		//world.setBlockState(new BlockPos(x + 3, y + 1, z + 0), Blocks.oak_door.getDefaultState(), 3);
		//world.setBlockState(new BlockPos(x + 4, y + 1, z + 0), Blocks.oak_door.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 1, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 1, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 1, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 1, z + 1), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 1, z + 1), Blocks.crafting_table.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 1, z + 1), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 1, z + 1), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 1, z + 1), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 1, z + 1), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 1, z + 1), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 1, z + 2), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 1, z + 2), Blocks.brewing_stand.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 1, z + 2), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 1, z + 2), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 1, z + 2), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 1, z + 2), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 1, z + 2), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 1, z + 3), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 1, z + 3), Blocks.brewing_stand.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 1, z + 3), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 1, z + 3), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 1, z + 3), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 1, z + 3), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 1, z + 3), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 1, z + 4), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 1, z + 4), Blocks.brewing_stand.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 1, z + 4), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 1, z + 4), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 1, z + 4), Blocks.light_weighted_pressure_plate.getDefaultState(),
				0);
		world.setBlockState(new BlockPos(x + 5, y + 1, z + 4), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 1, z + 4), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 1, z + 4), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 1, z + 5), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 1, z + 5), Blocks.brewing_stand.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 1, z + 5), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 1, z + 5), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 1, z + 5), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 1, z + 5), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 1, z + 5), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 1, z + 5), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 1, z + 6), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 1, z + 6), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 1, z + 6), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 1, z + 6), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 1, z + 6), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 1, z + 6), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 1, z + 6), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 1, z + 6), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 1, z + 7), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 1, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 1, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 1, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 1, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 1, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 1, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 1, z + 7), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 1, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 1, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 1, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 1, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 1, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 1, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 1, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 1, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 2, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 2, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 2, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 2, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 2, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 2, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 2, z + 1), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 2, z + 1), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 2, z + 1), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 2, z + 1), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 2, z + 1), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 2, z + 1), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 2, z + 1), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 2, z + 1), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 2, z + 2), Blocks.glass_pane.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 2, z + 2), Blocks.wooden_slab.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 2, z + 2), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 2, z + 2), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 2, z + 2), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 2, z + 2), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 2, z + 2), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 2, z + 2), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 2, z + 3), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 2, z + 3), Blocks.glass_pane.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 2, z + 3), Blocks.wooden_slab.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 2, z + 3), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 2, z + 3), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 2, z + 3), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 2, z + 3), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 2, z + 3), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 2, z + 4), Blocks.glass_pane.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 2, z + 4), Blocks.wooden_slab.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 2, z + 4), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 2, z + 4), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 2, z + 4), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 2, z + 4), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 2, z + 4), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 2, z + 4), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 2, z + 5), Blocks.glass_pane.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 2, z + 5), Blocks.wooden_slab.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 2, z + 5), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 2, z + 5), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 2, z + 5), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 2, z + 5), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 2, z + 5), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 2, z + 5), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 2, z + 6), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 2, z + 6), Blocks.oak_fence.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 2, z + 6), Blocks.brewing_stand.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 2, z + 6), Blocks.brewing_stand.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 2, z + 6), Blocks.brewing_stand.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 2, z + 6), Blocks.brewing_stand.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 2, z + 6), Blocks.oak_fence.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 2, z + 6), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 2, z + 7), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 2, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 2, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 2, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 2, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 2, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 2, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 2, z + 7), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 2, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 2, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 2, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 2, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 2, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 2, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 2, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 2, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 3, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 3, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 3, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 3, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 3, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 3, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 3, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 3, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 3, z + 1), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 3, z + 1), Blocks.glowstone.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 3, z + 1), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 3, z + 1), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 3, z + 1), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 3, z + 1), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 3, z + 1), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 3, z + 1), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 3, z + 2), Blocks.glass_pane.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 3, z + 2), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 3, z + 2), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 3, z + 2), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 3, z + 2), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 3, z + 2), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 3, z + 2), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 3, z + 2), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 3, z + 3), Blocks.glass_pane.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 3, z + 3), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 3, z + 3), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 3, z + 3), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 3, z + 3), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 3, z + 3), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 3, z + 3), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 3, z + 4), Blocks.glass_pane.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 3, z + 4), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 3, z + 4), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 3, z + 4), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 3, z + 4), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 3, z + 4), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 3, z + 4), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 3, z + 4), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 3, z + 5), Blocks.glass_pane.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 3, z + 5), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 3, z + 5), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 3, z + 5), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 3, z + 5), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 3, z + 5), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 3, z + 5), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 3, z + 5), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 3, z + 6), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 3, z + 6), Blocks.oak_fence.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 3, z + 6), Blocks.wooden_slab.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 3, z + 6), Blocks.wooden_slab.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 3, z + 6), Blocks.wooden_slab.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 3, z + 6), Blocks.wooden_slab.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 3, z + 6), Blocks.oak_fence.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 3, z + 6), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 3, z + 7), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 3, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 3, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 3, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 3, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 3, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 3, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 3, z + 7), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 3, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 3, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 3, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 3, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 3, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 3, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 3, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 3, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 4, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 4, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 4, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 4, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 4, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 4, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 4, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 4, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 4, z + 1), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 4, z + 1), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 4, z + 1), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 4, z + 1), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 4, z + 1), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 4, z + 1), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 4, z + 1), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 4, z + 1), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 4, z + 2), Blocks.glass_pane.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 4, z + 2), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 4, z + 2), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 4, z + 2), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 4, z + 2), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 4, z + 2), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 4, z + 2), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 4, z + 2), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 4, z + 3), Blocks.glass_pane.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 4, z + 3), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 4, z + 3), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 4, z + 3), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 4, z + 3), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 4, z + 3), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 4, z + 3), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 4, z + 4), Blocks.glass_pane.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 4, z + 4), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 4, z + 4), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 4, z + 4), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 4, z + 4), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 4, z + 4), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 4, z + 4), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 4, z + 4), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 4, z + 5), Blocks.glass_pane.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 4, z + 5), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 4, z + 5), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 4, z + 5), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 4, z + 5), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 4, z + 5), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 4, z + 5), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 4, z + 5), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 4, z + 6), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 4, z + 6), Blocks.oak_fence.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 4, z + 6), Blocks.brewing_stand.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 4, z + 6), Blocks.brewing_stand.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 4, z + 6), Blocks.brewing_stand.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 4, z + 6), Blocks.brewing_stand.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 4, z + 6), Blocks.oak_fence.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 4, z + 6), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 4, z + 7), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 4, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 4, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 4, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 4, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 4, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 4, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 4, z + 7), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 4, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 4, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 4, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 4, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 4, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 4, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 4, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 4, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 5, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 5, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 5, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 5, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 5, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 5, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 5, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 5, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 5, z + 1), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 5, z + 1), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 5, z + 1), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 5, z + 1), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 5, z + 1), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 5, z + 1), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 5, z + 1), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 5, z + 1), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 5, z + 2), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 5, z + 2), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 5, z + 2), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 5, z + 2), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 5, z + 2), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 5, z + 2), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 5, z + 2), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 5, z + 2), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 5, z + 3), Blocks.glass_pane.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 5, z + 3), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 5, z + 3), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 5, z + 3), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 5, z + 3), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 5, z + 3), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 5, z + 3), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 5, z + 3), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 5, z + 4), Blocks.glass_pane.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 5, z + 4), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 5, z + 4), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 5, z + 4), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 5, z + 4), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 5, z + 4), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 5, z + 4), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 5, z + 4), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 5, z + 5), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 5, z + 5), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 5, z + 5), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 5, z + 5), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 5, z + 5), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 5, z + 5), Blocks.air.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 5, z + 5), Blocks.bookshelf.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 5, z + 5), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 5, z + 6), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 5, z + 6), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 5, z + 6), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 5, z + 6), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 5, z + 6), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 5, z + 6), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 5, z + 6), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 5, z + 6), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 5, z + 7), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 5, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 5, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 5, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 5, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 5, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 5, z + 7), Blocks.planks.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 5, z + 7), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 5, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 5, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 5, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 5, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 5, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 5, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 5, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 5, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 6, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 6, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 6, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 6, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 6, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 6, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 6, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 6, z + 0), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 6, z + 1), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 6, z + 1), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 6, z + 1), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 6, z + 1), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 6, z + 1), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 6, z + 1), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 6, z + 1), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 6, z + 1), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 6, z + 2), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 6, z + 2), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 6, z + 2), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 6, z + 2), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 6, z + 2), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 6, z + 2), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 6, z + 2), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 6, z + 2), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 6, z + 3), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 6, z + 3), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 6, z + 3), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 6, z + 3), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 6, z + 3), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 6, z + 3), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 6, z + 3), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 6, z + 3), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 6, z + 4), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 6, z + 4), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 6, z + 4), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 6, z + 4), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 6, z + 4), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 6, z + 4), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 6, z + 4), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 6, z + 4), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 6, z + 5), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 6, z + 5), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 6, z + 5), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 6, z + 5), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 6, z + 5), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 6, z + 5), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 6, z + 5), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 6, z + 5), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 6, z + 6), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 6, z + 6), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 6, z + 6), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 6, z + 6), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 6, z + 6), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 6, z + 6), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 6, z + 6), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 6, z + 6), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 6, z + 7), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 6, z + 7), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 6, z + 7), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 6, z + 7), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 6, z + 7), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 6, z + 7), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 6, z + 7), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 6, z + 7), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 0, y + 6, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 1, y + 6, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 2, y + 6, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 3, y + 6, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 4, y + 6, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 5, y + 6, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 6, y + 6, z + 8), Blocks.brick_block.getDefaultState(), 0);
		world.setBlockState(new BlockPos(x + 7, y + 6, z + 8), Blocks.brick_block.getDefaultState(), 0);

		IBlockState iblockstate1 = Blocks.bed.getDefaultState().withProperty(BlockBed.OCCUPIED, Boolean.valueOf(false))
				.withProperty(BlockBed.FACING, EnumFacing.NORTH)
				.withProperty(BlockBed.PART, BlockBed.EnumPartType.FOOT);
		IBlockState soundtype = iblockstate1.withProperty(BlockBed.PART, BlockBed.EnumPartType.HEAD);

		world.setBlockState(new BlockPos(x + 5, y + 1, z + 1), soundtype, 1);
		world.setBlockState(new BlockPos(x + 5, y + 1, z + 2), iblockstate1, 2);

		world.setBlockState(new BlockPos(x + 5, y + 1, z + 3), Blocks.ladder.getDefaultState(), 4);
		world.setBlockState(new BlockPos(x + 5, y + 2, z + 3), Blocks.ladder.getDefaultState(), 4);
		world.setBlockState(new BlockPos(x + 5, y + 3, z + 3), Blocks.ladder.getDefaultState(), 4);
		world.setBlockState(new BlockPos(x + 5, y + 4, z + 3), Blocks.ladder.getDefaultState(), 4);

		IBlockState iblockstate = Blocks.oak_door.getDefaultState().withProperty(BlockDoor.FACING, EnumFacing.NORTH)
				.withProperty(BlockDoor.HINGE, BlockDoor.EnumHingePosition.LEFT).withProperty(BlockDoor.POWERED, false)
				.withProperty(BlockDoor.OPEN, false);
		IBlockState iblockstate3 = Blocks.oak_door.getDefaultState().withProperty(BlockDoor.FACING, EnumFacing.NORTH)
				.withProperty(BlockDoor.HINGE, BlockDoor.EnumHingePosition.RIGHT).withProperty(BlockDoor.POWERED, false)
				.withProperty(BlockDoor.OPEN, false);

		world.setBlockState(new BlockPos(x + 3, y + 1, z + 0),
				iblockstate.withProperty(BlockDoor.HALF, BlockDoor.EnumDoorHalf.LOWER), 2);
		world.setBlockState(new BlockPos(x + 4, y + 1, z + 0),
				iblockstate3.withProperty(BlockDoor.HALF, BlockDoor.EnumDoorHalf.LOWER), 2);
		world.setBlockState(new BlockPos(x + 3, y + 2, z + 0),
				iblockstate.withProperty(BlockDoor.HALF, BlockDoor.EnumDoorHalf.UPPER), 2);
		world.setBlockState(new BlockPos(x + 4, y + 2, z + 0),
				iblockstate3.withProperty(BlockDoor.HALF, BlockDoor.EnumDoorHalf.UPPER), 2);

		world.setBlockState(new BlockPos(x + 3, y + 0, z - 1),
				Blocks.oak_stairs.getDefaultState().withProperty(BlockStairs.FACING, EnumFacing.SOUTH), 0);
		world.setBlockState(new BlockPos(x + 4, y + 0, z - 1),
				Blocks.oak_stairs.getDefaultState().withProperty(BlockStairs.FACING, EnumFacing.SOUTH), 0);

		//NBTTagCompound tag = playerIn.getEntityData();
		SpeedForceHandler.tag.setBoolean("barryAllenLabBuilt", true);

		return new ActionResult(EnumActionResult.PASS, itemstackIn);
	}
}

